// Generated by https://quicktype.io

export interface PlacesResponse {
  type: string;
  query: string[];
  features: Feature[];
  attribution: string;
}

export interface Feature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: Properties;
  text_es: string;
  language_es?: Language;
  place_name_es: string;
  text: string;
  language?: Language;
  place_name: string;
  matching_text?: string;
  matching_place_name?: string;
  bbox: number[];
  center: number[];
  geometry: Geometry;
  context: Context[];
}

export interface Context {
  id: ID;
  short_code: ShortCode;
  wikidata: Wikidata;
  text_es: Text;
  language_es: Language;
  text: Text;
  language: Language;
}

export enum ID {
  Country11374003121964510 = "country.11374003121964510",
  Region7670481310034610 = "region.7670481310034610",
}

export enum Language {
  Es = "es",
}

export enum ShortCode {
  PE = "pe",
  PELim = "PE-LIM",
}

export enum Text {
  Lima = "Lima",
  Perú = "Perú",
}

export enum Wikidata {
  Q211795 = "Q211795",
  Q419 = "Q419",
}

export interface Geometry {
  type: string;
  coordinates: number[];
}

export interface Properties {
  wikidata?: string;
}
